const ADD_PRODUCT_CART =  'ADD_PRODUCT_CART'
const REMOVE_PRODUCT_CART = 'REMOVE_PRODUCT_CART'
const CLEAR_PRODUCT_CART = 'CLEAR_PRODUCT_CART'

export {
    ADD_PRODUCT_CART,
    REMOVE_PRODUCT_CART,
    CLEAR_PRODUCT_CART
}